### ISSUE TITLE
Yat doesn't launch on Debian

### ISSUE THREAD

**Issue by rapha8l** [LucaT1/yat#11]
Hi,
I tried your release, even if yat is executed, nothing is displayed and no error messages
(Debian testing)

thanks

**Comment by lucat1** [comment]
I am working on fixing this!

**Comment by lucat1** [comment]
Ping @rapha8l.
Should be fixed in master now. You can check oht the [latest relesease](https://github.com/LucaT1/yat/releases/tag/v0.1.1)

If you still see the error open another issue with the contents from the DevTools

**Comment by rapha8l** [comment]
Hi, it works after manual creation of ~/.yat, ~/.yat/node_modules and copying config.js to .yat
thanks

**Comment by lucat1** [comment]
Yep thx for the fix, but i'd like to solve this:heart:
Could we talk on Slack or discord to solve this? 

UPDATE:
Fixed on master, if you want you can compile it locally and test, otherwise you can wait for a few hours for a release fixing this, and adding live config-reload

**Comment by rapha8l** [comment]
Thanks, if needed I'm more on IRC but I can use slack if needed

**Comment by lucat1** [comment]
Please try to contact me on Discord as `LucaT#7910`:heart:

The new release `0.1.2` is out with the fix for this!
